apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-monitoring-app
  name: java-monitoring-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: java-monitoring-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-monitoring-app
    spec:
      containers:
      - image: jmalmeid/java-monitoring-test:latest
        imagePullPolicy: Always
        name: java-monitoring
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: java-monitoring-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-monitoring-app
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: java-monitoring-ingress
spec:
  rules:
  - host: java.example.com
    http:
      paths:
      - backend:
          serviceName: java-monitoring-svc
          servicePort: 8080
        path: /
---
